### ISSUE TITLE
Console Error Startup

### ISSUE THREAD

**Issue by LucidAPs** [anhcraft/AdvancedKeep#4]
[10:09:52 ERROR]: [org.bukkit.craftbukkit.v1_14_R1.CraftServer] A flag already exists by the name keep-exp initializing AdvancedKeep v1.4.9 (Is it up to date?)
com.sk89q.worldguard.protection.flags.registry.FlagConflictException: A flag already exists by the name keep-exp
        at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.forceRegister(SimpleFlagRegistry.java:87) ~[?:?]
        at com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:63) ~[?:?]
        at dev.anhcraft.advancedkeep.integrations.WGFlags.<init>(WGFlags.java:18) ~[?:?]
        at dev.anhcraft.advancedkeep.AdvancedKeep.onLoad(AdvancedKeep.java:162) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.14.4.jar:git-Paper-214]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-214]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-214]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by anhcraft** [comment]
Hi, @LucidAPs looks like the error happened since you had reloaded the plugin with PlugMan (or another plugin like that). 
Try to stop the server and enable it again. The plugin seems to work fine for me (with latest WorldGuard and WorldEdit).
If it still does not work, provide your server's log so I can get further info.

**Comment by LucidAPs** [comment]
This was a server startup error, i didn't reload the plugin.

**Comment by anhcraft** [comment]
So, you should try to update WorldEdit/WorldGuard to the latest. 
And if you previously used _KeepMyLife_, then remove the _KeepMyLife.jar_ since it is duplicate of AdvancedKeep.jar
.
If it still does not work, give me your server's log (via Discord or the forum if you want to keep it private)
